apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: k8smaestro
            - name: POSTGRESQL_PASSWORD
              value: k8smaestro
            - name: POSTGRESQL_USERNAME
              value: odoo
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  selector:
    matchLabels:
      app: odoo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-app
    spec:
      containers:
      - name: odoo-app
        image: bitnami/odoo
        ports:
          - containerPort: 8069
            protocol: TCP
            name: app
        env:
          - name: ODOO_DATABASE_HOST
            value: "postgresql.odoo.svc.cluster.local"
          - name: ODOO_DATABASE_PORT_NUMBER
            value: "5432"
          - name: ODOO_DATABASE_NAME
            value: k8smaestro
          - name: ODOO_DATABASE_USER
            value: odoo
          - name: ODOO_DATABASE_ADMIN_PASSWORD
            value: k8smaestro
          - name: ODOO_DATABASE_PASSWORD
            value: k8smaestro
          - name: ODOO_EMAIL
            value: user@example.com
          - name: ODOO_PASSWORD
            value: bitnami
---
apiVersion: v1
kind: Service
metadata:
  namespace: odoo
  name: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  namespace: odoo
  name: odoo-public
spec:
  ports:
    - port: 80
      targetPort: 8069
      protocol: TCP
  type: ClusterIP
  selector:
    app: odoo-app