apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: odoo-configmap
  namespace: odoo
data:
  DB_USER: "odoo"
---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: odoo
type: Opaque
data:
  DB_PASSWORD: azhzbWFlc3Rybw==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo
  namespace: odoo
spec:
  storageClassName: "standard-rwo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: k8smaestro
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret 
                  key: DB_PASSWORD
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: odoo-configmap
                  key: DB_USER
          volumeMounts:
            - name: postgres-storage
              mountPath: /bitnami/postgresql
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
spec:
  selector:
    matchLabels:
      app: odoo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo-app
    spec:    
      volumes:
        - name: odoo-storage
          persistentVolumeClaim:
            claimName: pvc-odoo
      containers:
      - name: odoo-app
        image: bitnami/odoo
        ports:
          - containerPort: 8069
            protocol: TCP
            name: app
        env:
          - name: ODOO_DATABASE_HOST
            value: "postgresql.odoo.svc.cluster.local"
          - name: ODOO_DATABASE_PORT_NUMBER
            value: "5432"
          - name: ODOO_DATABASE_NAME
            value: k8smaestro
          - name: ODOO_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: odoo-configmap
                key: DB_USER
          - name: ODOO_DATABASE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odoo-secret 
                key: DB_PASSWORD
          - name: ODOO_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: odoo-secret 
                key: DB_PASSWORD
          - name: ODOO_EMAIL
            value: user@example.com
          - name: ODOO_PASSWORD
            value: bitnami
        volumeMounts:
            - name: odoo-storage
              mountPath: /bitnami/odoo

---
apiVersion: v1
kind: Service
metadata:
  namespace: odoo
  name: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  namespace: odoo
  name: odoo-public
spec:
  ports:
    - port: 80
      targetPort: 8069
      protocol: TCP
  type: ClusterIP
  selector:
    app: odoo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  namespace: odoo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: odoo-public
            port: 
              number: 80